version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - absjoin
  - figsize
  - getch
  - kbhit
  - labjack
  - libqretprop
  - Modbus
  - Nikhil
  - pyproject
  - pyqtgraph
  - QRET
  - showlegend
  - skiprows
  - teststand
  - xaxes
  - yaxes
  - ylim
ignoreWords: []
import: []
